# Generated by Django 5.2.4 on 2025-07-06 22:47

import django.core.validators
import library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_alter_author_name_alter_book_image_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='editor',
            field=models.CharField(default='desconocido', max_length=70, validators=[library.models.validate_min_length]),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(error_messages={'unique': 'Ya existe un autor con ese nombre.'}, max_length=50, unique=True, validators=[library.models.validate_min_length]),
        ),
        migrations.AlterField(
            model_name='book',
            name='library_code',
            field=models.CharField(error_messages={'unique': 'Ya existe un libro con ese código.'}, max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener el formato 99-999', regex='^\\d{2}-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('A', 'Disponible'), ('B', 'Prestado'), ('U', 'No disponible')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(error_messages={'unique': 'Ya existe una categoria con ese nombre.'}, max_length=50, unique=True, validators=[library.models.validate_min_length]),
        ),
    ]
